### ISSUE TITLE
Add tests against other sites to ensure accuracy

### ISSUE THREAD

**Issue by uchagani** [zainhussaini/salat#2]
As-salamu alaykum, it would be great if you could add tests against other sites or APIs to ensure accuracy.  Maybe https://aladhan.com/prayer-times-api ?

I am the author of [prayer-times-calculator](https://github.com/uchagani/prayer-times-calculator ) and it is used inside [Home Assistant](https://www.home-assistant.io/).  It would be great if we could migrate to a non-cloud solution and your library looks very promising.  However, it would be great to ensure accuracy before we start any sort of migration to a non-cloud solution.

**Comment by zainhussaini** [comment]
Walaikum assalam, yes I could definitely use more test coverage, especially around edge cases. I prefer to use hardcoded tests instead of relying on an external API. This makes the tests more robust and easier to run.

If you could provide a list of what other cases you want tests for, I can add them inshaAllah.

**Comment by uchagani** [comment]
My concern is more around ensuring accuracy of the timings by comparing it to another source.

**Comment by zainhussaini** [comment]
Oh I see, actually I do already test against another source. I test against https://www.islamicfinder.org/prayer-times/, and you can see the tests at https://github.com/zainhussaini/salat/blob/main/tests/test_methods.py.
